export * from './Color';
export * from './Layout';
export * from './Root';
export * from './Profile';
export * from './Provider';
export * from './sportConfig';
import normalize from 'react-native-normalize'
import { StyleSheet } from "react-native"
import { COLOR } from "./Color"
import { LAYOUT } from "./Layout"

export const profileStyles = StyleSheet.create({
    container : {
        // backgroundColor:COLOR.baseBackgroundColor,
    },
    header:{
        backgroundColor:COLOR.headerColor,
        height:LAYOUT.window.height*0.085,
        justifyContent:'flex-start'
    },
    back:{
        padding:LAYOUT.window.width*0.02,
        flexDirection:'row',
        alignItems:'center'
    },
    headerBodyText:{
        textAlign:'center',
        width:LAYOUT.window.width*0.83,
        fontSize:LAYOUT.window.width*0.04,
        color:COLOR.whiteColor,
        fontWeight:'bold'
    },
    userstyle:{
        alignItems:'center',
        justifyContent:'center',
        padding:LAYOUT.window.width*0.05
    },
    avatar:{
        borderColor: COLOR.whiteColor,
        borderWidth: 1.5,
        width:LAYOUT.window.width*0.2,
        height:LAYOUT.window.width*0.2,
        borderRadius:LAYOUT.window.width*0.15
    },
    userInfoText:{
        textAlign:'center',
        color:COLOR.whiteColor,
        fontWeight:'bold',
        fontSize:LAYOUT.window.width*0.03,
        padding:LAYOUT.window.width*0.01
    },

    accordion:{
        width:LAYOUT.window.width*0.8,
        paddingTop:LAYOUT.window.width*0.03
    },
    accordionitem:{
        flexDirection: "row",
        paddingTop: LAYOUT.window.width*0.02,
        paddingBottom: LAYOUT.window.width*0.02,
        alignItems: "center"
    },
    accordionitemtext:{
        padding: LAYOUT.window.width*0.01,
        fontSize:LAYOUT.window.width*0.031,
        color:COLOR.whiteColor,
        fontWeight:'600',
    },
    accordiontext:{
        fontWeight:'bold',
        color:COLOR.whiteColor,
        fontSize:LAYOUT.window.width*0.031,
        paddingLeft: LAYOUT.window.width*0.02
    },
    accordiontext1:{
        color:COLOR.white2Color,
        fontSize:LAYOUT.window.width*0.031,
        paddingLeft: LAYOUT.window.width*0.02,
        fontWeight:'600',
    },
    accordionitemleft:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'flex-start',
        paddingLeft:LAYOUT.window.width*0.02
    },
    closeIcon:{
        fontWeight:"bold"
    },
    tabStyle:{
        backgroundColor:COLOR.baseBackgroundColor,
        height:LAYOUT.window.height*0.07
    },


    label:{
        color:COLOR.whiteColor,
        fontSize:normalize(18)
    },
    input:{
        color:COLOR.whiteColor,
        fontSize:normalize(18)
    },
    item:{
        padding:normalize(10),
        alignItems:'center',
        justifyContent:'center',
    },
    form:{
        alignItems:'center',
        justifyContent:'center',
    },


    daterangeText:{
        borderWidth:1,
        borderColor:COLOR.greenColor,
        height:normalize(30),
        borderRadius:normalize(15),
        textAlign:'center',
        textAlignVertical:'center',
        fontSize:normalize(18),
        color:COLOR.whiteColor,
    },


    TRheader: {
        height: LAYOUT.window.height*0.05,
        backgroundColor: COLOR.table.headerColor
    },
    Ttext: {
        textAlign: 'center',
        fontWeight: '400',
        fontSize:normalize(13)
    },
    Trow: {
        height: LAYOUT.window.height*0.06,
        backgroundColor: COLOR.table.row2Color
    },
    Theader:{
        borderWidth: 1,
        borderColor:COLOR.table.borderColor
    },
    TdataWrapper:{
        backgroundColor:COLOR.table.row2Color
    }
})

export const baseStyles = StyleSheet.create({

    Button:{
        height:LAYOUT.window.height*0.05,
        backgroundColor:COLOR.greenColor,
        paddingHorizontal:normalize(35),
        alignItems:'center',
        justifyContent:'center',
    },
    ButtonText:{
        color:COLOR.whiteColor,
        fontWeight:'700',
        fontSize:normalize(16),
    },

    Radius5:{
        borderRadius:5
    },
    Radius10:{
        borderRadius:10
    },
    Hidden:{
        overflow:'hidden'
    },
    baseBack:{
        backgroundColor:COLOR.baseBackgroundColor,
    },
    ROW:{
        flexDirection:'row'
    },
    Column:{
        flexDirection:'column'
    },
    Wrap:{
        flexWrap:'wrap'
    },
    Jbetween:{
        justifyContent:'space-between'
    },
    Jcenter:{
        justifyContent:'center'
    },
    Jstart:{
        justifyContent:'flex-start'
    },
    Jend:{
        justifyContent:'flex-end'
    },
    Acenter:{
        alignItems:'center'
    },
    Astart:{
        alignItems:'flex-start'
    },
    Aend:{
        alignItems:'flex-end'
    },
    Tcenter:{
        textAlign:'center'
    },
    Tright:{
        textAlign:'right'
    },
    Tleft:{
        textAlign:'left'
    },
    Tvcenter:{
        textAlignVertical:'center'
    },
    FBOLD:{
        fontWeight:'bold'
    },
    FW300:{
        fontWeight:'300'
    },
    FW400:{
        fontWeight:'400'
    },
    FW700:{
        fontWeight:'700'
    },
    F12:{
        fontSize:normalize(12)
    },
    F13:{
        fontSize:normalize(13)
    },
    F14:{
        fontSize:normalize(14)
    },
    F15:{
        fontSize:normalize(15)
    },
    F16:{
        fontSize:normalize(16)
    },
    F17:{
        fontSize:normalize(17)
    },
    F18:{
        fontSize:normalize(18)
    },
    F19:{
        fontSize:normalize(19)
    },
    F20:{
        fontSize:normalize(20)
    },
    F21:{
        fontSize:normalize(21)
    },
    F22:{
        fontSize:normalize(22)
    },
    F23:{
        fontSize:normalize(23)
    },
    F24:{
        fontSize:normalize(24)
    },
    F25:{
        fontSize:normalize(25)
    },
    F26:{
        fontSize:normalize(26)
    },
    F27:{
        fontSize:normalize(27)
    },
    F28:{
        fontSize:normalize(28)
    },
    F29:{
        fontSize:normalize(29)
    },
    F30:{
        fontSize:normalize(30)
    },
    F35:{
        fontSize:normalize(35)
    },
    F36:{
        fontSize:normalize(36)
    },
    F40:{
        fontSize:normalize(40)
    },
    F45:{
        fontSize:normalize(45)
    },
    F48:{
        fontSize:normalize(48)
    },
    F50:{
        fontSize:normalize(50)
    },
    F55:{
        fontSize:normalize(55)
    },
    F72:{
        fontSize:normalize(72)
    },


    M0:{
        margin:normalize(0)
    },
    M5:{
        margin:normalize(5)
    },
    M10:{
        margin:normalize(10)
    },
    M20:{
        margin:normalize(20)
    },
    M30:{
        margin:normalize(30)
    },
    M40:{
        margin:normalize(40)
    },
    M50:{
        margin:normalize(50)
    },

    MT0:{
        marginTop:0
    },
    MT5:{
        marginTop:normalize(5)
    },
    MT10:{
        marginTop:normalize(10)
    },
    MT15:{
        marginTop:normalize(15)
    },
    MT20:{
        marginTop:normalize(20)
    },
    MT30:{
        marginTop:normalize(30)
    },
    MT40:{
        marginTop:normalize(40)
    },
    MT50:{
        marginTop:normalize(50)
    },
    MT70:{
        marginTop:normalize(70)
    },
    MT80:{
        marginTop:normalize(80)
    },
    MT100:{
        marginTop:normalize(100)
    },

    MB10:{
        marginBottom:normalize(10)
    },
    MB15:{
        marginBottom:normalize(15)
    },
    MB20:{
        marginBottom:normalize(20)
    },
    MB30:{
        marginBottom:normalize(30)
    },
    MB40:{
        marginBottom:normalize(40)
    },
    MB50:{
        marginBottom:normalize(50)
    },
    MB60:{
        marginBottom:normalize(60)
    },
    MB70:{
        marginBottom:normalize(70)
    },


    MV5:{
        marginVertical:normalize(5)
    },

    MV10:{
        marginVertical:normalize(10)
    },
    MV20:{
        marginVertical:normalize(20)
    },
    MV30:{
        marginVertical:normalize(30)
    },
    MV40:{
        marginVertical:normalize(40)
    },
    MV50:{
        marginVertical:normalize(50)
    },

    MH5:{
        marginHorizontal:normalize(5)
    },
    MH10:{
        marginHorizontal:normalize(10)
    },
    MH20:{
        marginHorizontal:normalize(20)
    },
    MH25:{
        marginHorizontal:normalize(25)
    },
    MH30:{
        marginHorizontal:normalize(30)
    },
    MH40:{
        marginHorizontal:normalize(40)
    },
    MH50:{
        marginHorizontal:normalize(50)
    },

    MR10:{
        marginRight:normalize(10)
    },
    MR20:{
        marginRight:normalize(20)
    },
    MR30:{
        marginRight:normalize(30)
    },
    MR40:{
        marginRight:normalize(40)
    },
    MR50:{
        marginRight:normalize(50)
    },

    ML10:{
        marginLeft:normalize(10)
    },
    ML20:{
        marginLeft:normalize(20)
    },
    ML30:{
        marginLeft:normalize(30)
    },
    ML40:{
        marginLeft:normalize(40)
    },
    ML50:{
        marginLeft:normalize(50)
    },


    P0:{
        padding:0
    },
    P5:{
        padding:normalize(5)
    },
    P10:{
        padding:normalize(10)
    },
    P20:{
        padding:normalize(20)
    },
    P30:{
        padding:normalize(30)
    },
    P40:{
        padding:normalize(40)
    },
    P50:{
        padding:normalize(50)
    },

    PB10:{
        paddingBottom:normalize(10)
    },
    PB20:{
        paddingBottom:normalize(20)
    },
    PB30:{
        paddingBottom:normalize(30)
    },
    PB40:{
        paddingBottom:normalize(40)
    },
    PB50:{
        paddingBottom:normalize(50)
    },

    PT0:{
        paddingTop:0
    },
    PT5:{
        paddingTop:normalize(5)
    },
    PT10:{
        paddingTop:normalize(10)
    },
    PT20:{
        paddingTop:normalize(20)
    },
    PT25:{
        paddingTop:normalize(25)
    },
    PT30:{
        paddingTop:normalize(30)
    },
    PT40:{
        paddingTop:normalize(40)
    },
    PT50:{
        paddingTop:normalize(50)
    },
    PT70:{
        paddingTop:normalize(70)
    },
    PT100:{
        paddingTop:normalize(100)
    },
    PT130:{
        paddingTop:normalize(130)
    },
    PT150:{
        paddingTop:normalize(150)
    },
    PT200:{
        paddingTop:normalize(200)
    },

    PL10:{
        paddingLeft:normalize(10)
    },
    PL15:{
        paddingLeft:normalize(15)
    },
    PL20:{
        paddingLeft:normalize(20)
    },
    PL25:{
        paddingLeft:normalize(25)
    },
    PL30:{
        paddingLeft:normalize(30)
    },
    PL40:{
        paddingLeft:normalize(40)
    },
    PL50:{
        paddingLeft:normalize(50)
    },

    PR10:{
        paddingRight:normalize(10)
    },
    PR20:{
        paddingRight:normalize(20)
    },
    PR30:{
        paddingRight:normalize(30)
    },
    PR40:{
        paddingRight:normalize(40)
    },
    PR50:{
        paddingRight:normalize(50)
    },

    PV5:{
        paddingVertical:normalize(5)
    },
    PV10:{
        paddingVertical:normalize(10)
    },
    PV20:{
        paddingVertical:normalize(20)
    },
    PV15:{
        paddingVertical:normalize(15)
    },
    PV30:{
        paddingVertical:normalize(30)
    },
    PV40:{
        paddingVertical:normalize(40)
    },
    PV50:{
        paddingVertical:normalize(50)
    },
    PV150:{
        paddingVertical:normalize(150)
    },

    PH5:{
        paddingHorizontal:normalize(5)
    },
    PH10:{
        paddingHorizontal:normalize(10)
    },
    PH15:{
        paddingHorizontal:normalize(15)
    },
    PH20:{
        paddingHorizontal:normalize(20)
    },
    PH25:{
        paddingHorizontal:normalize(25)
    },
    PH30:{
        paddingHorizontal:normalize(30)
    },
    PH40:{
        paddingHorizontal:normalize(40)
    },
    PH50:{
        paddingHorizontal:normalize(50)
    },
    PH100:{
        paddingHorizontal:normalize(100)
    },


    H10:{
        height:normalize(10)
    },
    H20:{
        height:normalize(20)
    },
    H30:{
        height:normalize(30)
    },
    H40:{
        height:normalize(40)
    },
    H50:{
        height:normalize(50)
    },
    H55:{
        height:normalize(55)
    },
    H60:{
        height:normalize(60)
    },
    H80:{
        height:normalize(80)
    },
    H100:{
        height:normalize(100)
    },
    H150:{
        height:normalize(150)
    },

    W10:{
        width:normalize(10)
    },
    W20:{
        width:normalize(20)
    },
    W30:{
        width:normalize(30)
    },
    W40:{
        width:normalize(40)
    },
    W50:{
        width:normalize(50)
    },

    W25P:{
        width:'25%'
    },
    W30P:{
        width:'30%'
    },
    W50P:{
        width:'50%'
    },
    W60P:{
        width:'60%'
    },
    W75P:{
        width:'75%'
    },
    W100P:{
        width:'100%'
    },

    H25P:{
        height:'25%'
    },
    H50P:{
        height:'50%'
    },
    H60P:{
        height:'60%'
    },
    H75P:{
        height:'75%'
    },
    H100P:{
        height:'100%'
    },

})